<?php
/**
 * @file
 * Code for the Mega Menu feature.
 */

include_once 'navarts_mega_menu.features.inc';

/**
 * Implements hook_init()
 */

function navarts_mega_menu_init() {
  $path = drupal_get_path('module', 'navarts_mega_menu');
  // Styles the superfish markup to play with Drupal.
  drupal_add_css($path . '/css/menu_style.css', 'file');
  // Responsive Behavior
  drupal_add_css($path . '/css/responsive.css', 'file');
  drupal_add_js($path . '/js/responsive.js', 'file');
  /* Temporarily added fonts.com ref here */
  drupal_add_js('http://fast.fonts.com/jsapi/ab00f64c-51b5-4c25-9cac-0e22938ef7a3.js');
}
